### ISSUE TITLE
Couple Bugs

### ISSUE THREAD

**Issue by hherbol** [ValarDragon/Fractals#2]
Sooo... I have my students browsing Github and reading code to learn.  One of which was interested in your fractal code.  Just a heads up on a couple bugs:

1. In koch_snowflake.py, around line 12, you give a file name.  The colon is an issue (likely only windows, but could be other operating systems as well).  I recommend swapping it for and underscore.

2. In config.py (same folder as koch_snowflake), your scaling factor of 1/3 equates to 0.  Cast either the numerator or denominator to a float via float(num), or simply do 1.0 / 3.0.  In python3 1/3 equates to 0.33333; however, I noticed you use PIL, which I believe is only available in python2.

**Comment by ValarDragon** [comment]
I have been using python3, I didn't realize it had that backwards compatibility issue! 
Also the colon must be a windows only issue, that will be fixed!

Thanks for reporting the bugs! Also I'm pretty excited that someone has <hopefully> been able to learn something from the code I wrote!
